### PR TITLE
QoL and cleanup

### PR DESCRIPTION
**Pull request by RobinGeens**
- Various small fixes to improve user experience
- Changes that still need to be made alongside upgrading Zigzag to version 3, but that missed the deadline of the CONVOLVE demo

Task list:

- [ ] Correctly configure project as Python package (including typing)
- [ ] Cleanup old files and lab folders
- [ ]  Move the input folder back into `root/zigzag` to make it part of the package
- [ ] Update the documentation
- [ ] Speed up execution time through minor improvements
- [ ] Extend ONNX parsing 
- [ ] Improve usability of output files
- [ ] Repair `RemoveUnusedMemoryStage` (and please give this a better name)
- [ ] Fix other typing errors
- [ ] Fix (at least some) Pylint errors

Other ideas:
- [ ] Provide one example output json file and annotate it to describe what all of the numbers mean
- [ ] Remove the concept of core allocation altogether
- [ ] Clean up the API: do we need so many API functions? They all do the same with different configurations
- [ ] Allow the user to not specify a mapping file and generate all mappings (since core allocation is no longer needed and memory operand links has a default)

### CODE REVIEW

**Comment by Andful** [comment]
Could you make this an issue 🥲? and handle each task as a pull request? (and tick each box as the fixes are being implemented with linked pull request)?

I am willing to help if you would like.

**Comment by asyms** [comment]
> Could you make this an issue 🥲? and handle each task as a pull request? (and tick each box as the fixes are being implemented with linked pull request)?
> 
> I am willing to help if you would like.

I think this is a good idea. However some can fit together in one. I think the following grouping makes sense?

1. Correctly configure project as a package + Moving of inputs/ folder + lab folder cleanup
2. Fixing typing/linting errors
3. Fixing and renaming of RemoveUnusedMemoryStage. We can define a "Single-layer-at-a-time" is without any memory removal, "Layer-by-Layer" is with memory removal.
4. Extending ONNX parsing (What do you mean exactly with this @RobinGeens?)
5. Updating documentation + Improve usabililty of output files + Annotate an example output file
6. API cleanup

@RobinGeens let me know which points the commits you made here tackle enitrely or partially.
If I missed something or if you think another grouping makes sense, we can discuss it here.

**Comment by Andful** [comment]
I think from the commit messages:

* 1 - add py.typed and cerberus package to pyproject.toml c8ba727
* 1 - remove labs 976c2d8
* 1 - Add __init__.py in every subdir fc1b318
* 1 - remove devcontainer and validation 747340e
* 5 - fix doxygen input files bc95f0c
* 2 - fix some more errors and types ff506ce
* 2 (but there seem to be a fix unrelated to typing) - some more error fixes 56e90db
* 4 - support onnx parsing of gemm with input size 3 6e76944
* 4 (I think?) - allow arbitrary number of input operand sources a30e8be
* 4 (I think?) - Convert GEMM format O=W*I to O=I*W - ec796c3
* 4 - Use layer name from ONNX model instead of default 4094deb
* 4 - Restore mapping based on layer name 6afa9d7
* (speedup?) - Some minor speedup improvements 528c623
* 5 - fix output file dump c423ce5

Maybe some changes in 4 should be in 6, not sure.

I think you can easily make separate pull requests by branching off this branch and using `git rebase -i` to drop commits that are unrelated to the pull request.

**Comment by RobinGeens** [comment]
Aha yes, good suggestion @Andful .
Here is my suggestion:

1. Correctly configure project as a package + Moving of inputs/ folder + lab folder cleanup
**1.** Fixing typing/linting errors _(these were on-the-go changes and I don't plan to exclusively work on linting issues at the moment)_
3. Fixing and renaming of RemoveUnusedMemoryStage. We can define a "Single-layer-at-a-time" is without any memory removal, "Layer-by-Layer" is with memory removal.
**3. Also fix or remove the other files that no longer work with the new version (e.g. PEArrayScaling)**
4. Extending ONNX parsing (What do you mean exactly with this @RobinGeens?) _E.g. support for multi-dimensional tensors and quantization. This should indeed not be part of QoL and cleanup_
5. Updating documentation + Improve usabililty of output files + Annotate an example output file _This is also very urgent in my opinion, but we can do this in a separate PR_
6. API cleanup

For the commits:
1 - add py.typed and cerberus package to pyproject.toml https://github.com/KULeuven-MICAS/zigzag/commit/c8ba727e59b9994ed670d3b56f7698a26c5069b9
1 - remove labs https://github.com/KULeuven-MICAS/zigzag/commit/976c2d8ef4c6932a0370c9f1964b75d3d541b46e
1 - Add init.py in every subdir https://github.com/KULeuven-MICAS/zigzag/commit/fc1b31889ec9aca97f0038019964219a59bd2b9e
1 - remove devcontainer and validation https://github.com/KULeuven-MICAS/zigzag/commit/747340e5fa680df6a839bb5392ca3d7c65089143
**1** - fix doxygen input files https://github.com/KULeuven-MICAS/zigzag/commit/bc95f0cae2378ef39ce12bd75eea753bd4a4007d  _this relates to a working configuration_
**1** - fix some more errors and types https://github.com/KULeuven-MICAS/zigzag/commit/ff506cecb59b8f4f1cbecf23d5d85ca03f3decda
2 (but there seem to be a fix unrelated to typing) - some more error fixes https://github.com/KULeuven-MICAS/zigzag/commit/56e90db19bde016d33176ff078cc97c7e9d448f3
4 - support onnx parsing of gemm with input size 3 https://github.com/KULeuven-MICAS/zigzag/commit/6e76944a347541f6e169e5fdaed75879d43e7c21
4 - allow arbitrary number of input operand sources https://github.com/KULeuven-MICAS/zigzag/commit/a30e8bef3f2a735dd7952f1bc7e18cc5ee1f7220
4  - Convert GEMM format O=WI to O=IW - https://github.com/KULeuven-MICAS/zigzag/commit/ec796c3849221cfba217e4e152fded51f96d19c5
**1** - Use layer name from ONNX model instead of default https://github.com/KULeuven-MICAS/zigzag/commit/4094deb7513be0c99659860940941be042fef9f6 _This was supposed to be part of the CONVOLVE demo but somehow the commit got overwritten. I see this as an urgent fix_
**1** - Restore mapping based on layer name https://github.com/KULeuven-MICAS/zigzag/commit/6afa9d774ea6218aaa9e136c4974c2d001ecf52b
(speedup?) - Some minor speedup improvements https://github.com/KULeuven-MICAS/zigzag/commit/528c623f55c61a4ef2de3e310a4e670c4a7bd23c  _These are minor improvements that have a big impact on simulation time. I don't plan on doing many other so either append this to another PR or make a very small PR with 1 or 2 changes_
5 - fix output file dump https://github.com/KULeuven-MICAS/zigzag/commit/c423ce5e013d3f04e971b1bfc574bb52785b3838

**Comment by RobinGeens** [comment]
I have created multiple branches and PRs to replace this PR. The changes related to ONNX parsing (in `extend-onnx` branch) doesn't have a PR yet because it is WIP.

**Pull request closed without merging**
