### PR TITLE
Update project configuration and remove clutter after CONVOLVE demo

### PR DESCRIPTION
**Pull request by RobinGeens**

### CODE REVIEW

**Comment by RobinGeens** [comment]
The tests don't seem to pass because they timeout after 6h. Can we reduce the test suite? Either only do 3.11 or 3.12, or simply reduce the number of tested configurations (or randomize which architecture/workload is tested)

**Comment by asyms** [comment]
> The tests don't seem to pass because they timeout after 6h. Can we reduce the test suite? Either only do 3.11 or 3.12, or simply reduce the number of tested configurations (or randomize which architecture/workload is tested)

I have updated the pytest to only use Python 3.11 as this is also the version we minimally require in pyproject.toml.

**Comment by asyms** [comment]
@RobinGeens I will move the inputs back to zigzag/inputs in this PR? Or was this planned in a different PR?

**Comment by RobinGeens** [comment]
> @RobinGeens I will move the inputs back to zigzag/inputs in this PR? Or was this planned in a different PR?

This should be this PR :)

**Comment by RobinGeens** [comment]
> > The tests don't seem to pass because they timeout after 6h. Can we reduce the test suite? Either only do 3.11 or 3.12, or simply reduce the number of tested configurations (or randomize which architecture/workload is tested)
> 
> I have updated the pytest to only use Python 3.11 as this is also the version we minimally require in pyproject.toml.

This doesn't seem to be enough to prevent timeouts, so maybe we should randomize which workload is tested for each of the architectures?

**Review by asyms — APPROVED** [review]

**Pull request merged**
