### PR TITLE
Fix runner

### PR DESCRIPTION
**Pull request by RobinGeens**
Update CI/CD with pre-commit (the previously used ruff action was no longer working so an update was needed).

The large number of changes can be attributed to reformatting. The manual changes to the code are very limited.

### CODE REVIEW

**Review by jorendumoulin — APPROVED** [review]
Allright, just a few notes:

- This will fuck up all outstanding PRs, so be careful when you want to merge stuff
- Maybe set some style defaults for ruff in your `pyproject.toml`. Most notably the line length which seems to defaul to 80, which can make your code somewhat unreadable

**Comment by jorendumoulin** [comment]
This will also fuck up all people's local branches, so maybe best to sync up with everyone before doing this

**Comment by RobinGeens** [comment]
> This will also fuck up all people's local branches, so maybe best to sync up with everyone before doing this

In what way? Would running `pre-commit` locally before attempting to merge solve most of the issues?

**Comment by jorendumoulin** [comment]
I'm not sure, but I don't think so. I think there will be a lot of conflicts, but you can always try this out locally to check this.

**Pull request merged**
