### PR TITLE
Update pyproject.toml to reflect requirements.txt

### PR DESCRIPTION
**Pull request by Andful**

### CODE REVIEW

**Comment by RobinGeens** [comment]
I'm not sure whether `typeguard` and `pytest` should be part of the project dependencies since they are only used for testing? I don't think the tests are shipped together with the project

**Comment by asyms** [comment]
Robin is correct. We need those packages to be put in the optional 'dev' part (https://peps.python.org/pep-0508/#extras).
The project can then be installed including these packages using:

`pip install zigzag-dse[dev]`

**Comment by Andful** [comment]
I will update the pull request!

**Comment by asyms** [comment]
Great! Could you also update the documentation to reflect this? That would be this part:

https://github.com/KULeuven-MICAS/zigzag/blob/master/docs/source/contribute.rst#upgrading-the-project-version-for-zigzag-developers

**Comment by Andful** [comment]
* Updated the documentation.
* I added `ruff` both to `pyproject.toml` and `requiriments.txt`.
* In the linting workflow, I removed installing from `requiriments.txt`, `pip install .[dev]` is enough.

**Review by asyms — APPROVED** [review]

**Pull request merged**
